package main

import (
	"fmt"
	"strconv"
)

/*
	AppendQuoteRune appends a single-quoted Go character literal representing the rune, as generated by QuoteRune, to dst and returns the extended buffer.
	func AppendQuoteRune(dst []byte, r rune) []byte
*/

func main() {
	b := []byte("rune:")
	b = strconv.AppendQuoteRune(b, '☺')
	fmt.Println(string(b))
}