package main

import (
	"fmt"
	"strconv"
)

/*
	AppendQuote appends a double-quoted Go string literal representing s, as generated by Quote, to dst and returns the extended buffer.
	func AppendQuote(dst []byte, s string) []byte
*/

func main() {
	b := []byte("quote:")
	b = strconv.AppendQuote(b, `"Fran & Freddie's Diner"`)
	fmt.Println(string(b))

}